# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - '**/*.md'
    - '**/*.adoc'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - '**/*.md'
    - '**/*.adoc'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Should be skipped?
        env:
          COMMIT_FILTER: "[skip ci]"
        run: |
          # The build should be skipped when commit contains value defined in COMMIT_FILTER
          # Based on: https://github.com/marketplace/actions/skip-based-on-commit-message
          last_commit_log=$(git log -1 --pretty=format:"%s %b")

          readonly local is_merge_commit=$(echo "$last_commit_log" | egrep -c "Merge [a-zA-Z0-9]* into [a-zA-Z0-9]*")
          if "$is_merge_commit" ; then
            readonly local commit_id=$(echo "$last_commit_log" | sed 's/Merge //' | sed 's/ into [a-zA-Z0-9]*//')
            last_commit_log=$(git log -1 --pretty="%s %b" "$commit_id")
          fi
          echo "last commit log: $last_commit_log"

          readonly local filter_count=$(echo "$last_commit_log" | fgrep -c "$COMMIT_FILTER")
          echo "number of occurence of '$COMMIT_FILTER' in '$last_commit_log': $filter_count"

          if [[ "$filter_count" -eq 0 ]]; then
            echo "all good, continue"
          else
            echo "the last commit log \"$last_commit_log\" contains \"$COMMIT_FILTER\", stopping"
            exit 78
          fi
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish
        if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
        run: |
          git tag "v$(./gradlew properties | grep ^version: | sed 's/^version: //')"
          git push --tags
          ./gradlew -Dgithub.token=${{ secrets.GITHUB_TOKEN }} publish -s